/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.telas.telasEntradaIndividual;

import Classes.Campanha;
import Classes.Item;
import Classes.ItemDTO;
import Classes.Personagem;
import Classes.PersonagemClasseDTO;
import Controller.ControladorItem;
import Controller.ControladorPersonagem;
import Controller.GerenciadorControladores;
import GUI.formularios.adicionarItemPersonagem;
import GUI.formularios.edicaoPersonagem;
import GUI.formularios.removerItemPersonagem;
import GUI.telas.TelaCampanhas;
import GUI.telas.TelaClasses;
import GUI.telas.TelaInicial;
import GUI.telas.TelaItens;
import GUI.telas.TelaJogadores;
import GUI.telas.TelaMissoes;
import GUI.telas.TelaMonstros;
import GUI.telas.TelaPersonagens;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author Portu
 */
public class TelaPersonagemIndividual extends javax.swing.JFrame {

    private final java.awt.Frame parent;
    private final Personagem personagem;
    private final GerenciadorControladores controladores;
    private final ControladorPersonagem ctrlPersonagem;
    private final ControladorItem ctrlItem;
    private Runnable aoFechar;

    public TelaPersonagemIndividual(java.awt.Frame parent, Personagem personagem, GerenciadorControladores controladores, Runnable aoFechar) {
        this.parent = parent;
        this.personagem = personagem;
        this.controladores = controladores;
        this.ctrlPersonagem = controladores.obter(ControladorPersonagem.class);
        this.ctrlItem = controladores.obter(ControladorItem.class);
        this.aoFechar = aoFechar;
        initComponents();

        titulo.setText(personagem.getNome());
        carregarConteudo();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (TelaPersonagemIndividual.this.aoFechar != null) {
                    TelaPersonagemIndividual.this.aoFechar.run();
                }
            }
        });
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaPersonagem = new javax.swing.JTextArea();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonAdicionarClasse = new javax.swing.JButton();
        buttonRemoverClasse = new javax.swing.JButton();
        buttonAdicionarItem = new javax.swing.JButton();
        buttonRemoverItem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonCampanhas = new javax.swing.JButton();
        buttonInicio = new javax.swing.JButton();
        buttonJogadores = new javax.swing.JButton();
        buttonPersonagens = new javax.swing.JButton();
        buttonItens = new javax.swing.JButton();
        buttonMonstros = new javax.swing.JButton();
        buttonClasses = new javax.swing.JButton();
        buttonMissoes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(125, 125, 156));

        textAreaPersonagem.setColumns(20);
        textAreaPersonagem.setRows(5);
        jScrollPane1.setViewportView(textAreaPersonagem);

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setForeground(new java.awt.Color(255, 0, 0));
        buttonExcluir.setText("Excluir");

        buttonAdicionarClasse.setText("Adicionar classe");

        buttonRemoverClasse.setText("Remover classe");
        buttonRemoverClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverClasseActionPerformed(evt);
            }
        });

        buttonAdicionarItem.setText("Adicionar item");
        buttonAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarItemActionPerformed(evt);
            }
        });

        buttonRemoverItem.setText("Remover item");
        buttonRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonExcluir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonAdicionarClasse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoverClasse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAdicionarItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoverItem))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionarClasse)
                    .addComponent(buttonRemoverClasse)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonAdicionarItem)
                        .addComponent(buttonRemoverItem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEditar)
                    .addComponent(buttonExcluir))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 104, 156));

        buttonCampanhas.setText("Campanhas");
        buttonCampanhas.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonCampanhas.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonCampanhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCampanhasActionPerformed(evt);
            }
        });

        buttonInicio.setText("Inicio");
        buttonInicio.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonInicio.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioActionPerformed(evt);
            }
        });

        buttonJogadores.setText("Jogadores");
        buttonJogadores.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonJogadores.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogadoresActionPerformed(evt);
            }
        });

        buttonPersonagens.setText("Personagens");
        buttonPersonagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonagensActionPerformed(evt);
            }
        });

        buttonItens.setText("Itens");
        buttonItens.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonItens.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItensActionPerformed(evt);
            }
        });

        buttonMonstros.setText("Monstros");
        buttonMonstros.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonMonstros.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonMonstros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMonstrosActionPerformed(evt);
            }
        });

        buttonClasses.setText("Classes");
        buttonClasses.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonClasses.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClassesActionPerformed(evt);
            }
        });

        buttonMissoes.setLabel("Missões");
        buttonMissoes.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonMissoes.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonMissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMissoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPersonagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCampanhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonJogadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMonstros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMissoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buttonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(buttonCampanhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPersonagens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMonstros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(buttonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(229, 29, 32));

        titulo.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("dngoiajsdbdgoai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioActionPerformed
        this.aoFechar = null;

        TelaInicial dialog = new TelaInicial(controladores);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonInicioActionPerformed

    private void buttonCampanhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCampanhasActionPerformed
        this.aoFechar = null;

        TelaCampanhas dialog = new TelaCampanhas(this, true, controladores, () -> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCampanhasActionPerformed

    private void buttonJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogadoresActionPerformed
        this.aoFechar = null;

        TelaJogadores dialog = new TelaJogadores(this, true, controladores, () -> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonJogadoresActionPerformed

    private void buttonPersonagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonagensActionPerformed
        this.aoFechar = null;

        TelaPersonagens dialog = new TelaPersonagens(this, true, controladores, () -> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonPersonagensActionPerformed

    private void buttonClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClassesActionPerformed
        this.aoFechar = null;

        TelaClasses dialog = new TelaClasses(this, true, controladores, () -> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonClassesActionPerformed

    private void buttonMonstrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMonstrosActionPerformed
        this.aoFechar = null;

        TelaMonstros dialog = new TelaMonstros(this, true, controladores, () -> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonMonstrosActionPerformed

    private void buttonItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItensActionPerformed
        this.aoFechar = null;

        TelaItens dialog = new TelaItens(this, true, controladores, () -> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonItensActionPerformed

    private void buttonMissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMissoesActionPerformed
        this.aoFechar = null;

        TelaMissoes dialog = new TelaMissoes(this, true, controladores, () -> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonMissoesActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        edicaoPersonagem dialog = new edicaoPersonagem(this, true, personagem, controladores, () -> {
            new TelaPersonagemIndividual(this, personagem, controladores, () -> {
                new TelaInicial(controladores).setVisible(true);
            });
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonRemoverClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRemoverClasseActionPerformed

    private void buttonRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverItemActionPerformed
        this.setVisible(false);

        removerItemPersonagem dialog = new removerItemPersonagem(this, true, controladores, personagem, () -> {
            carregarConteudo();
            this.setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonRemoverItemActionPerformed

    private void buttonAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarItemActionPerformed
        this.setVisible(false);

        adicionarItemPersonagem dialog = new adicionarItemPersonagem(this, true, controladores, personagem, () -> {
            carregarConteudo();
            this.setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonAdicionarItemActionPerformed

    private void carregarConteudo() {
        try {
            textAreaPersonagem.setText(personagem.toStringResumo());

            ArrayList<Campanha> campanhas = ctrlPersonagem.obterCampanhasParticipando(personagem.getIdPersonagem());
            ArrayList<ItemDTO> inventario = ctrlPersonagem.obterInventarioDoPersonagem(personagem.getIdPersonagem());
            ArrayList<PersonagemClasseDTO> classes = ctrlPersonagem.obterClassesDoPersonagem(personagem.getIdPersonagem());

            StringBuilder sb = new StringBuilder();

            sb.append("\n=== CAMPANHAS ===\n");
            for (Campanha c : campanhas) {
                sb.append(c).append("\n");
            }

            sb.append("\n=== INVENTÁRIO ===\n");
            for (ItemDTO i : inventario) {
                Item item = ctrlItem.buscarItem(i.getIdItem());
                sb.append(item).append(" QTD: " + i.getQuantidade()).append("\n");
            }

            sb.append("\n=== Classes ===\n");
            for (PersonagemClasseDTO cl : classes) {
                sb.append(cl).append("\n");
            }

            textAreaPersonagem.append(sb.toString());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar conteúdo do personagem: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarClasse;
    private javax.swing.JButton buttonAdicionarItem;
    private javax.swing.JButton buttonCampanhas;
    private javax.swing.JButton buttonClasses;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonInicio;
    private javax.swing.JButton buttonItens;
    private javax.swing.JButton buttonJogadores;
    private javax.swing.JButton buttonMissoes;
    private javax.swing.JButton buttonMonstros;
    private javax.swing.JButton buttonPersonagens;
    private javax.swing.JButton buttonRemoverClasse;
    private javax.swing.JButton buttonRemoverItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaPersonagem;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
