/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.formularios;

import Classes.Campanha;
import Classes.Item;
import Classes.ItemDTO;
import Classes.Jogador;
import Classes.Missao;
import Classes.Monstro;
import Classes.Personagem;
import Controller.ControladorCampanha;
import Controller.ControladorItem;
import Controller.ControladorMissao;
import Controller.ControladorMonstro;
import Controller.ControladorPersonagem;
import Controller.GerenciadorControladores;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Portu
 */
public class edicaoMissao extends javax.swing.JDialog {

    private final java.awt.Frame parent;
    private final GerenciadorControladores controladores;
    private final ControladorMissao ctrlMissao;
    private final ControladorMonstro ctrlMonstro;
    private final ControladorPersonagem ctrlPersonagem;
    private final ControladorItem ctrlItem;
    private final ControladorCampanha ctrlCampanha;
    private final Missao missao;
    private final Runnable aoFechar;

    public edicaoMissao(java.awt.Frame parent, boolean modal, GerenciadorControladores controladores, Missao missao, Runnable aoFechar) {
        super(parent, modal);
        this.parent = parent;
        this.controladores = controladores;
        this.ctrlMissao = controladores.obter(ControladorMissao.class);
        this.ctrlMonstro = controladores.obter(ControladorMonstro.class);
        this.ctrlPersonagem = controladores.obter(ControladorPersonagem.class);
        this.ctrlItem = controladores.obter(ControladorItem.class);
        this.ctrlCampanha = controladores.obter(ControladorCampanha.class);
        this.missao = missao;
        this.aoFechar = aoFechar;

        initComponents();
        configurarEventos();
        carregarDados();
        atualizarEstadoBotaoCadastrar();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (edicaoMissao.this.aoFechar != null) {
                    edicaoMissao.this.aoFechar.run();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonCadastrar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        comboMestre = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMonstros = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoXp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboCampanha = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPersonagens = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listRecompensas = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(125, 125, 156));

        buttonCadastrar.setText("Editar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonLimpar.setLabel("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome: ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mestre: ");

        jScrollPane2.setViewportView(listMonstros);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Monstros: ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Experiencia: ");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Campanha: ");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Personagens: ");

        jScrollPane3.setViewportView(listPersonagens);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recompensas: ");

        jScrollPane4.setViewportView(listRecompensas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(buttonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(buttonCadastrar)
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboMestre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoXp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(104, 104, 104)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboMestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrar)
                    .addComponent(buttonLimpar))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(152, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(campoXp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(comboCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(68, 68, 68)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)))
        );

        jPanel1.setBackground(new java.awt.Color(229, 29, 32));

        titulo.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Edição de Missão");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        campoNome.setText("");
        campoXp.setText("");
        jTextArea1.setText("");
        comboCampanha.setSelectedItem(null);

        listPersonagens.clearSelection();
        listMonstros.clearSelection();
        listRecompensas.clearSelection();

        atualizarEstadoBotaoCadastrar();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        try {
            String nome = campoNome.getText().trim();
            String descricao = jTextArea1.getText().trim();
            int xpBonus = Integer.parseInt(campoXp.getText().trim());

            Campanha campanhaSelecionada = (Campanha) comboCampanha.getSelectedItem();
            if (campanhaSelecionada == null) {
                JOptionPane.showMessageDialog(this, "Selecione uma campanha.");
                return;
            }

            String idCampanha = campanhaSelecionada.getIdCampanha();
            String idMissao = missao.getIdMissao();

            ctrlMissao.atualizarMissao(idMissao, nome, descricao, xpBonus);

            sincronizarParticipantes(idCampanha, idMissao);
            sincronizarInimigos(idMissao);
            sincronizarRecompensas(idMissao);

            missao.setNome(nome);
            missao.setDescricao(descricao);
            missao.setXpBonus(xpBonus);

            JOptionPane.showMessageDialog(this,
                    "Missão atualizada com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "XP bônus deve ser um número inteiro válido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao atualizar missão: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Validação",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void carregarDados() {
        try {

            javax.swing.DefaultListModel<Personagem> modelPersonagens = new javax.swing.DefaultListModel<>();
            for (Personagem personagem : ctrlPersonagem.listarTodosOsPersonagens()) {
                modelPersonagens.addElement(personagem);
            }
            listPersonagens.setModel(modelPersonagens);
            listPersonagens.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            listPersonagens.clearSelection();

            javax.swing.DefaultListModel<Monstro> modelMonstros = new javax.swing.DefaultListModel<>();
            for (Monstro monstro : ctrlMonstro.listarTodosOsMonstros()) {
                modelMonstros.addElement(monstro);
            }
            listMonstros.setModel(modelMonstros);
            listMonstros.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            listMonstros.clearSelection();

            javax.swing.DefaultListModel<Item> modelItens = new javax.swing.DefaultListModel<>();
            for (Item item : ctrlItem.listarTodosOsItens()) {
                modelItens.addElement(item);
            }
            listRecompensas.setModel(modelItens);
            listRecompensas.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            listRecompensas.clearSelection();

            comboCampanha.removeAllItems();

            ArrayList<Campanha> campanhas = ctrlCampanha.listarTodasAsCampanhas();
            for (Campanha campanha : campanhas) {
                comboCampanha.addItem(campanha);
            }
            comboCampanha.setSelectedItem(null);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar dados: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void configurarEventos() {
        buttonCadastrar.setEnabled(false);

        javax.swing.event.DocumentListener listener = new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                atualizarEstadoBotaoCadastrar();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                atualizarEstadoBotaoCadastrar();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                atualizarEstadoBotaoCadastrar();
            }
        };

        campoNome.getDocument().addDocumentListener(listener);
        campoXp.getDocument().addDocumentListener(listener);
        jTextArea1.getDocument().addDocumentListener(listener);

        comboCampanha.addItemListener(e -> {
            if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED
                    || e.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
                atualizarEstadoBotaoCadastrar();
            }
        });

        javax.swing.event.ListSelectionListener selectionListener = e -> {
            if (!e.getValueIsAdjusting()) {
                atualizarEstadoBotaoCadastrar();
            }
        };

        listPersonagens.addListSelectionListener(selectionListener);
        listMonstros.addListSelectionListener(selectionListener);
        listRecompensas.addListSelectionListener(selectionListener);
    }

    private void atualizarEstadoBotaoCadastrar() {
        boolean nomePreenchido = !campoNome.getText().trim().isEmpty();
        boolean xpValido = textoEhInteiro(campoXp.getText().trim());
        boolean descricaoPreenchida = !jTextArea1.getText().trim().isEmpty();
        boolean campanhaSelecionada = comboCampanha.getSelectedIndex() != -1;

        boolean personagensSelecionados = !listPersonagens.isSelectionEmpty();
        boolean monstrosSelecionados = !listMonstros.isSelectionEmpty();
        boolean recompensasSelecionadas = !listRecompensas.isSelectionEmpty();

        buttonCadastrar.setEnabled(
                nomePreenchido
                && xpValido
                && descricaoPreenchida
                && campanhaSelecionada
                && personagensSelecionados

        );
    }

    private boolean textoEhInteiro(String texto) {
        if (texto == null || texto.isBlank()) {
            return false;
        }
        try {
            Integer.parseInt(texto);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private <T> void selecionarNoComboPorId(javax.swing.JComboBox<T> combo, java.util.function.Function<T, String> extratorId, String idBuscado) {
        if (idBuscado == null || idBuscado.isBlank()) {
            combo.setSelectedItem(null);
            return;
        }

        for (int i = 0; i < combo.getItemCount(); i++) {
            T item = combo.getItemAt(i);
            if (idBuscado.equals(extratorId.apply(item))) {
                combo.setSelectedIndex(i);
                return;
            }
        }

        combo.setSelectedItem(null);
    }

    private <T> void selecionarNaListaPorIds(javax.swing.JList<T> lista, java.util.function.Function<T, String> extratorId, java.util.Collection<String> idsSelecionados) {
        if (idsSelecionados == null || idsSelecionados.isEmpty()) {
            lista.clearSelection();
            return;
        }

        javax.swing.ListModel<T> model = lista.getModel();
        java.util.List<Integer> indices = new java.util.ArrayList<>();

        for (int i = 0; i < model.getSize(); i++) {
            T item = model.getElementAt(i);
            String id = extratorId.apply(item);

            if (idsSelecionados.contains(id)) {
                indices.add(i);
            }
        }

        int[] arrayIndices = indices.stream().mapToInt(Integer::intValue).toArray();
        lista.setSelectedIndices(arrayIndices);
    }

    private void selecionarDadosDaMissao() {
        try {

            String idCampanha = ctrlMissao.obterCampanhasDaMissao(missao.getIdMissao()).getFirst().getIdCampanha();

            selecionarNoComboPorId(comboCampanha, Campanha::getIdCampanha, idCampanha);

            // Aqui você precisa ter métodos que retornem os IDs vinculados à missão.
            java.util.List<Personagem> participantes = ctrlCampanha.listarParticipantesDaMissao(idCampanha, missao.getIdMissao());
            java.util.Set<String> idsPersonagens = new java.util.HashSet<>();
            for (Personagem p : participantes) {
                idsPersonagens.add(p.getIdPersonagem());
            }
            selecionarNaListaPorIds(listPersonagens, Personagem::getIdPersonagem, idsPersonagens);

            java.util.List<Monstro> monstros = ctrlMissao.listarInimigosDaMissao(missao.getIdMissao());
            java.util.Set<String> idsMonstros = new java.util.HashSet<>();
            for (Monstro m : monstros) {
                idsMonstros.add(m.getIdMonstro());
            }
            selecionarNaListaPorIds(listMonstros, Monstro::getIdMonstro, idsMonstros);

            java.util.List<ItemDTO> recompensas = ctrlMissao.listarRecompensasDaMissao(missao.getIdMissao());
            java.util.Set<String> idsItens = new java.util.HashSet<>();
            for (ItemDTO item : recompensas) {
                idsItens.add(item.getIdItem());
            }
            selecionarNaListaPorIds(listRecompensas, Item::getIdItem, idsItens);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao selecionar dados da missão: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void sincronizarParticipantes(String idCampanha, String idMissao) throws SQLException {
        java.util.List<Personagem> selecionados = listPersonagens.getSelectedValuesList();
        java.util.List<Personagem> atuais = ctrlCampanha.listarParticipantesDaMissao(idCampanha, idMissao);

        java.util.Set<String> idsSelecionados = new java.util.HashSet<>();
        for (Personagem p : selecionados) {
            idsSelecionados.add(p.getIdPersonagem());
        }

        java.util.Set<String> idsAtuais = new java.util.HashSet<>();
        for (Personagem p : atuais) {
            idsAtuais.add(p.getIdPersonagem());
        }

        for (Personagem p : atuais) {
            if (!idsSelecionados.contains(p.getIdPersonagem())) {
                ctrlCampanha.desvincularPersonagemDaMissao(idCampanha, idMissao, p.getIdPersonagem());
            }
        }

        for (Personagem p : selecionados) {
            if (!idsAtuais.contains(p.getIdPersonagem())) {
                ctrlCampanha.adicionarParticipanteAMissao(idCampanha, idMissao, p.getIdPersonagem());
            }
        }
    }

    private void sincronizarInimigos(String idMissao) throws SQLException {
        java.util.List<Monstro> selecionados = listMonstros.getSelectedValuesList();
        java.util.List<Monstro> atuais = ctrlMissao.listarInimigosDaMissao(idMissao);

        java.util.Set<String> idsSelecionados = new java.util.HashSet<>();
        for (Monstro m : selecionados) {
            idsSelecionados.add(m.getIdMonstro());
        }

        java.util.Set<String> idsAtuais = new java.util.HashSet<>();
        for (Monstro m : atuais) {
            idsAtuais.add(m.getIdMonstro());
        }

        for (Monstro m : atuais) {
            if (!idsSelecionados.contains(m.getIdMonstro())) {
                ctrlMissao.removerInimigo(idMissao, m.getIdMonstro());
            }
        }

        for (Monstro m : selecionados) {
            if (!idsAtuais.contains(m.getIdMonstro())) {
                ctrlMissao.adicionarInimigo(idMissao, m.getIdMonstro(), 1);
            }
        }
    }

    private void sincronizarRecompensas(String idMissao) throws SQLException {
        java.util.List<Item> selecionados = listRecompensas.getSelectedValuesList();
        java.util.List<ItemDTO> atuais = ctrlMissao.listarRecompensasDaMissao(idMissao);

        java.util.Set<String> idsSelecionados = new java.util.HashSet<>();
        for (Item item : selecionados) {
            idsSelecionados.add(item.getIdItem());
        }

        java.util.Set<String> idsAtuais = new java.util.HashSet<>();
        for (ItemDTO item : atuais) {
            idsAtuais.add(item.getIdItem());
        }

        for (ItemDTO item : atuais) {
            if (!idsSelecionados.contains(item.getIdItem())) {
                ctrlMissao.removerRecompensa(idMissao, item.getIdItem());
            }
        }

        for (Item item : selecionados) {
            if (!idsAtuais.contains(item.getIdItem())) {
                ctrlMissao.adicionarRecompensa(idMissao, item.getIdItem(), 1);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoXp;
    private javax.swing.JComboBox<Campanha> comboCampanha;
    private javax.swing.JComboBox<Jogador> comboMestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<Monstro> listMonstros;
    private javax.swing.JList<Personagem> listPersonagens;
    private javax.swing.JList<Item> listRecompensas;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
