/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.telas;

import Classes.Item;
import Classes.Jogador;
import Controller.ControladorJogador;
import Controller.GerenciadorControladores;
import GUI.formularios.cadastroJogador;
import GUI.telas.telasEntradaIndividual.TelaJogadorIndividual;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Portu
 */
public class TelaJogadores extends javax.swing.JFrame {

    private final java.awt.Frame parent;
    private final GerenciadorControladores controladores;
    private final ControladorJogador ctrlJogador;
    private final Runnable aoFechar;
    
    public TelaJogadores(java.awt.Frame parent, boolean modal, GerenciadorControladores controladores, Runnable aoFechar) {
        this.parent = parent;
        this.controladores = controladores;
        this.ctrlJogador = controladores.obter(ControladorJogador.class);
        this.aoFechar = aoFechar;
        
        initComponents();
        carregarJogadores();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (TelaJogadores.this.aoFechar != null) {
                    TelaJogadores.this.aoFechar.run();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        buttonCampanhas = new javax.swing.JButton();
        buttonInicio = new javax.swing.JButton();
        buttonJogadores = new javax.swing.JButton();
        buttonPersonagens = new javax.swing.JButton();
        buttonItens = new javax.swing.JButton();
        buttonMonstros = new javax.swing.JButton();
        buttonClasses = new javax.swing.JButton();
        buttonMissoes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        buttonCriar = new javax.swing.JButton();
        buttonAbrir = new javax.swing.JButton();
        comboJogadores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 104, 156));

        buttonCampanhas.setText("Campanhas");
        buttonCampanhas.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonCampanhas.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonCampanhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCampanhasActionPerformed(evt);
            }
        });

        buttonInicio.setText("Inicio");
        buttonInicio.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonInicio.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioActionPerformed(evt);
            }
        });

        buttonJogadores.setText("Jogadores");
        buttonJogadores.setEnabled(false);
        buttonJogadores.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonJogadores.setMinimumSize(new java.awt.Dimension(96, 23));

        buttonPersonagens.setText("Personagens");
        buttonPersonagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonagensActionPerformed(evt);
            }
        });

        buttonItens.setText("Itens");
        buttonItens.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonItens.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItensActionPerformed(evt);
            }
        });

        buttonMonstros.setText("Monstros");
        buttonMonstros.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonMonstros.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonMonstros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMonstrosActionPerformed(evt);
            }
        });

        buttonClasses.setText("Classes");
        buttonClasses.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonClasses.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClassesActionPerformed(evt);
            }
        });

        buttonMissoes.setLabel("Missões");
        buttonMissoes.setMaximumSize(new java.awt.Dimension(96, 23));
        buttonMissoes.setMinimumSize(new java.awt.Dimension(96, 23));
        buttonMissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMissoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPersonagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCampanhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonJogadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMonstros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMissoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buttonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(buttonCampanhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPersonagens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMonstros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(buttonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(125, 125, 156));

        buttonCriar.setText("Cadastrar novo jogador");
        buttonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCriarActionPerformed(evt);
            }
        });

        buttonAbrir.setText("Abrir página do jogador");
        buttonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbrirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrados:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCriar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(229, 29, 32));

        titulo.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Jogadores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioActionPerformed
        TelaInicial dialog = new TelaInicial(controladores);

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonInicioActionPerformed

    private void buttonCampanhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCampanhasActionPerformed
        TelaCampanhas dialog = new TelaCampanhas(this, true, controladores, ()-> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCampanhasActionPerformed

    private void buttonPersonagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonagensActionPerformed
        TelaPersonagens dialog = new TelaPersonagens(this, true, controladores, ()-> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_buttonPersonagensActionPerformed

    private void buttonClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClassesActionPerformed
        TelaClasses dialog = new TelaClasses(this, true, controladores, () -> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonClassesActionPerformed

    private void buttonMonstrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMonstrosActionPerformed
        TelaMonstros dialog = new TelaMonstros(this, true, controladores, ()-> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonMonstrosActionPerformed

    private void buttonItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItensActionPerformed
        TelaItens dialog = new TelaItens(this, true, controladores, ()-> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonItensActionPerformed

    private void buttonMissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMissoesActionPerformed
        TelaMissoes dialog = new TelaMissoes(this, true, controladores, ()-> {
            new TelaInicial(controladores).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonMissoesActionPerformed

    private void buttonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbrirActionPerformed
        Jogador jogadorSelecionado = (Jogador) comboJogadores.getSelectedItem();
        
        TelaJogadorIndividual dialog = new TelaJogadorIndividual(this, jogadorSelecionado, controladores, () -> {
            new TelaJogadores(this, true, controladores, () -> {
                new TelaInicial(controladores).setVisible(true);
            }).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonAbrirActionPerformed

    private void buttonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCriarActionPerformed
        cadastroJogador dialog = new cadastroJogador(this, true, controladores, () -> {
            new TelaJogadores(parent, true, controladores, () -> {
                new TelaInicial(controladores).setVisible(true);
            }).setVisible(true);
        });
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCriarActionPerformed

    private void carregarJogadores() {
        try {
            comboJogadores.removeAllItems();

            ArrayList<Jogador> jogadores = ctrlJogador.listarTodosOsJogadores();
            for (Jogador jogador : jogadores) {
                comboJogadores.addItem(jogador);
            }

            comboJogadores.setSelectedItem(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar jogadores: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbrir;
    private javax.swing.JButton buttonCampanhas;
    private javax.swing.JButton buttonClasses;
    private javax.swing.JButton buttonCriar;
    private javax.swing.JButton buttonInicio;
    private javax.swing.JButton buttonItens;
    private javax.swing.JButton buttonJogadores;
    private javax.swing.JButton buttonMissoes;
    private javax.swing.JButton buttonMonstros;
    private javax.swing.JButton buttonPersonagens;
    private javax.swing.JComboBox<Jogador> comboJogadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
